apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicinestockmicroservice-deployment
  labels:
    app: MedicineStockMicroService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MedicineStockMicroService  
  template:
    metadata:
      labels:
        app: MedicineStockMicroService
    spec:
      containers:
      - name: medicinestockmicroservice
        image: myfirstazurecr.azurecr.io/myfirstazurereo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: medicinevc
---
apiVersion: v1
kind: Service
metadata:
  name: medicinestockmicroservicevc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MedicineStockMicroService